services:
  dozzle:
    image: amir20/dozzle:latest
    labels:
      - com.centurylinklabs.watchtower.enable=true
    container_name: ${CONTAINER_NAME}_main
    environment:
      TZ: ${TZ:-Europe/Moscow}
      DOZZLE_AUTH_PROVIDER: simple
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./${CONTAINER_NAME}_data:/data
    restart: unless-stopped
    ports:
      - 8765:8080
