services:
  apprise_notification__bed:
    image: mazzolino/apprise-microservice:0.1
    container_name: ${CONTAINER_NAME}_bed
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    networks:
      - apprise_notification
    environment:
      NOTIFICATION_URLS: tgram://${TG_TOKEN_BED}/${TG_CHAT_ID_BED}
  apprise_notification__good:
    image: mazzolino/apprise-microservice:0.1
    container_name: ${CONTAINER_NAME}_good
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    networks:
      - apprise_notification
    environment:
      NOTIFICATION_URLS: tgram://${TG_TOKEN_GOOD}/${TG_CHAT_ID_GOOD}
#
# NetWorks
#
networks:
  apprise_notification: 
    external: true
