services:
  apprise_notification:
    image: mazzolino/apprise-microservice:0.1
    container_name: ${CONTAINER_NAME}_main
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    networks:
      - apprise_notification
    volumes:
      - ./${CONTAINER_NAME}_data/config:/config
      - ./${CONTAINER_NAME}_data/plugin:/plugin
      - ./${CONTAINER_NAME}_data/attach:/attach
    environment:
      NOTIFICATION_URLS: tgram://${TG_TOKEN}/${TG_CHAT_ID}
#
# NetWorks
#
networks:
  apprise_notification: 
    external: true
