name: immich

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    container_name: ${CONTAINER_NAME}_main
    volumes:
      - ${UPLOAD_LOCATION}:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: unless-stopped
    healthcheck:
      disable: false

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    container_name: ${CONTAINER_NAME}_ml
    volumes:
      - ./${CONTAINER_NAME}_data/cache:/cache
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      disable: false

  redis:
    image: docker.io/valkey/valkey:8@sha256:81db6d39e1bba3b3ff32bd3a1b19a6d69690f94a3954ec131277b9a26b95b3aa
    labels:
      - com.centurylinklabs.watchtower.enable=true
    container_name: ${CONTAINER_NAME}_redis
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    labels:
      - com.centurylinklabs.watchtower.enable=true
    container_name: ${CONTAINER_NAME}_db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_STORAGE_TYPE: 'HDD'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 128mb
    restart: unless-stopped
  #
  # BeckUps
  #
  ## main
  backup_restic__immich:
    extends:
      file: ../restic/restic-compose-base.yaml
      service: backup
    environment:
      BACKUP_CRON: "0 50 3 * * *"
      RESTIC_COMPRESSION: max
      PRE_COMMANDS: |-
        docker stop ${CONTAINER_NAME}_main
        docker stop ${CONTAINER_NAME}_db
      POST_COMMANDS_SUCCESS: |-
        docker start ${CONTAINER_NAME}_main
        docker start ${CONTAINER_NAME}_db
    volumes:
      - ${BASE_LOCATION}:/backup_data:ro
  ## prune
  prune_restic__immich:
    extends:
      file: ../restic/restic-compose-base.yaml
      service: prune
  ## chekc
  check_restic__immich:
    extends:
      file: ../restic/restic-compose-base.yaml
      service: check
#
# NetWorks
#
networks:
  apprise_notification: 
    external: true
