services:
  pb_app:
    image: jez500/pricebuddy:latest
    container_name: ${CONTAINER_NAME}_main
    labels:
      - autoheal-app=true
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./${CONTAINER_NAME}_data/storage:/app/storage
      - ./.env:/app/.env
    environment:
      DB_HOST: pb_database            # Name of the database service
      DB_USERNAME: pricebuddy         # Should match the MYSQL_USER in the database service
      DB_PASSWORD: pric3buddy         # Should match the MYSQL_PASSWORD in the database service
      DB_DATABASE: pricebuddy         # Should match the MYSQL_DATABASE in the database service
      APP_USER_EMAIL: admin@example.com     # Only used for seeding the database
      APP_USER_PASSWORD: admin        # Only used for seeding the database
      SCRAPER_BASE_URL: http://scraper:3000   # Url to Name of the scrapper service
      AFFILIATE_ENABLED: 'true'         # See https://pricebuddy.jez.me/support-project.html
    depends_on:
      pb_database:
        condition: service_healthy
  #
  # MySQL database
  #
  pb_database:
    image: mysql:8.2
    container_name: ${CONTAINER_NAME}_db
    labels:
      - autoheal-app=true
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pricebuddy
      MYSQL_USER: pricebuddy
      MYSQL_PASSWORD: pric3buddy
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./${CONTAINER_NAME}_data/database:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1m
  #
  # Seleniumbase scrapper
  #
  pb_scraper:
    image: jez500/seleniumbase-scrapper:latest
    container_name: ${CONTAINER_NAME}_scraper
    labels:
      - autoheal-app=true
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    ports:
      - 3030:3000 # Optional, if you want to access the scrapper api from the host machine
#
# NetWorks
#
networks: {}
