services:
  pb_app:
    image: jez500/pricebuddy:latest
    container_name: ${CONTAINER_NAME}_main
    labels:
      - autoheal-app=true
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./${CONTAINER_NAME}_data/storage:/app/storage
      - ./.env:/app/.env
    environment:
      ### APP
      # APP_KEY: echo "APP_KEY=base64:$(openssl rand -base64 32)" >> .env
      APP_USER_EMAIL: ${APP_USER_EMAIL:-admin@example.com}    
      APP_USER_PASSWORD: ${APP_USER_PASSWORD:-admin}       
      ### DB
      DB_HOST: ${CONTAINER_NAME}_db
      DB_DATABASE: ${DB_DATABASE:-pricebuddy}        
      DB_USERNAME: ${DB_USERNAME:-pricebuddy}        
      DB_PASSWORD: ${DB_PASSWORD:-pric3buddy}        
      ### Other
      SCRAPER_BASE_URL: http://${CONTAINER_NAME}_scraper:3000  
      AFFILIATE_ENABLED: 'true'        
    depends_on:
      pb_database:
        condition: service_healthy
  #
  # MySQL database
  #
  pb_database:
    image: mysql:8.2
    container_name: ${CONTAINER_NAME}_db
    labels:
      - autoheal-app=true
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-pricebuddy}
      MYSQL_USER: ${DB_USERNAME:-pricebuddy}
      MYSQL_PASSWORD: ${DB_PASSWORD:-pric3buddy}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./${CONTAINER_NAME}_data/database:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1m
  #
  # Seleniumbase scrapper
  #
  pb_scraper:
    image: jez500/seleniumbase-scrapper:latest
    container_name: ${CONTAINER_NAME}_scraper
    labels:
      - autoheal-app=true
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    ports:
      - 3030:3000 # Optional, if you want to access the scrapper api from the host machine
#
# NetWorks
#
networks: {}
