services:
  beszel:
    image: henrygd/beszel:latest
    container_name: ${CONTAINER_NAME}_main
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    environment:
      TZ: ${TZ:-Europe/Moscow}
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8090:8090
    volumes:
      - ./beszel_socket:/beszel_socket
      - ./${CONTAINER_NAME}_data/config:/beszel_data
  beszel-agent:
    image: henrygd/beszel-agent-intel
    container_name: ${CONTAINER_NAME}_lockal_agent
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./${CONTAINER_NAME}_data/agent:/var/lib/beszel-agent
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      - /home/.beszel:/extra-filesystems/sdb__home:ro
      - /media/.beszel:/extra-filesystems/sdc__media:ro
      - /backup/flash/.beszel:/extra-filesystems/sdd__flash:ro
    environment:
      TZ: ${TZ:-Europe/Moscow}
      LISTEN: ${LISTEN}
      KEY: ${KEY}
      TOKEN: ${TOKEN}
      HUB_URL: ${HUB_URL}
      SMART_DEVICES: ${SMART_DEVICES}
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/disk/by-uuid/${UUID_SDC}:/dev/sdc
      - /dev/disk/by-uuid/${UUID_SDD}:/dev/sdd
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
  # BeckUps
  ## main
  backup_restic__beszel:
    extends:
      file: ../restic/restic-compose-base.yaml
      service: backup
    volumes:
      - ./${CONTAINER_NAME}_data/config:/backup_data:ro
  ## prune
  prune_restic__beszel:
    extends:
      file: ../restic/restic-compose-base.yaml
      service: prune
  ## chekc
  check_restic__beszel:
    extends:
      file: ../restic/restic-compose-base.yaml
      service: check
#
# NetWorks
#
networks:
  apprise_notification: 
    external: true
